# Common table expressions

Using the northwind database

## 1. Write a CTE that lists the names and quantities of products with a unit price greater than $50.

In [25]:
import sqlite3
import pandas as pd

# Connect to your database (use a real .db file path if needed)
conn = sqlite3.connect('northwind.db')

# Run your SQL query1
query1 = """
WITH totalquants AS (
	SELECT ProductID, SUM(Quantity) AS total_quantity
	FROM OrderDetails
	GROUP BY ProductID
)
SELECT p.ProductName, t.total_quantity, p.Unit AS Unit
FROM Products p
JOIN totalquants t ON p.ProductID = t.ProductID
WHERE p.Price > 50;
"""

In [27]:
# Read the results into a pandas DataFrame
df = pd.read_sql_query(query1, conn)
df.head()

               ProductName  total_quantity                  Unit
0          Mishi Kobe Niku              20      18 - 500 g pkgs.
1         Carnarvon Tigers             106            16 kg pkg.
2   Sir Rodney's Marmalade             106         30 gift boxes
3  Thüringer Rostbratwurst             168  50 bags x 30 sausgs.
4            Côte de Blaye             239    12 - 75 cl bottles

In [13]:
df

               ProductName  total_quantity                  Unit
0          Mishi Kobe Niku              20      18 - 500 g pkgs.
1         Carnarvon Tigers             106            16 kg pkg.
2   Sir Rodney's Marmalade             106         30 gift boxes
3  Thüringer Rostbratwurst             168  50 bags x 30 sausgs.
4            Côte de Blaye             239    12 - 75 cl bottles
5    Manjimup Dried Apples             163      50 - 300 g pkgs.
6     Raclette Courdavault             346             5 kg pkg.

#### Expected results

|ProductName                     |Unit|
|--------------------------------|----|
|Mishi Kobe Niku                 |18 - 500 g pkgs.|
|Carnarvon Tigers                |16 kg pkg.|
|Sir Rodney's Marmalade          |30 gift boxes|
|Thüringer Rostbratwurst         |50 bags x 30 sausgs.|
|Côte de Blaye                   |12 - 75 cl bottles|
|Manjimup Dried Apples           |50 - 300 g pkgs.|
|Raclette Courdavault            |5 kg pkg.|

## 2. What are the top 5 most profitable products?

```sql
-- Your code down below
```

In [66]:

query_2 = """
  SELECT 
    p.ProductName,
    SUM(od.Quantity * p.Price) AS TotalRevenue
 FROM OrderDetails od
 JOIN Products p ON od.ProductID = p.ProductID
 GROUP BY p.ProductName
 ORDER BY TotalRevenue DESC
 LIMIT 5;
 """

In [67]:
# Read the results into a pandas DataFrame
df2 = pd.read_sql_query(query_2, conn)
df2

               ProductName  TotalRevenue
0            Côte de Blaye      62976.50
1  Thüringer Rostbratwurst      20796.72
2     Raclette Courdavault      19030.00
3           Tarte au sucre      16022.50
4        Camembert Pierrot      14620.00

#### Expected results
Alice Mutton is 6th

|ProductID                       |ProductName|TotalRevenue|
|--------------------------------|-----------|------------|
|-                             |-|-       |
|-                           |-|-       |
|-                            |-|-       |
|-                             |-|-       |
|-                              |-|-       |
|17                              |Alice Mutton|12909       |

## 3. Write a CTE that lists the top 5 categories by the number of products they have.

```sql
-- Your code down below
```

In [31]:
query3 = """
WITH CategoryProductCount AS (
    SELECT
        c.CategoryName,
        COUNT(p.ProductID) AS ProductCount
    FROM Categories c
    JOIN Products p ON c.CategoryID = p.CategoryID
    GROUP BY c.CategoryName
)
SELECT
    CategoryName,
    ProductCount
FROM CategoryProductCount
ORDER BY ProductCount DESC
LIMIT 5;
"""

In [34]:
# Read the results into a pandas DataFrame
df3 = pd.read_sql_query(query3, conn)
df3

     CategoryName  ProductCount
0     Confections            13
1       Beverages            12
2      Condiments            12
3         Seafood            12
4  Dairy Products            10

#### Expected result
|CategoryName                    |ProductCount|
|--------------------------------|------------|
|Confections                     |13          |
|Beverages                       |12          |
|Condiments                      |12          |
|Seafood                         |12          |
|Dairy Products                  |10          |

## 4. Write a CTE that shows the average order quantity for each product category.

In [44]:
query4 = """
WITH CategoryOrderQty AS (
    SELECT
        c.CategoryID,
        c.CategoryName,
        p.ProductID,
        p.ProductName,
        SUM(od.Quantity) AS TotalQuantity
    FROM OrderDetails od
    JOIN Products p ON od.ProductID = p.ProductID
    JOIN Categories c ON p.CategoryID = c.CategoryID
    GROUP BY c.CategoryID, c.CategoryName, p.ProductID, p.ProductName
)
SELECT
    CategoryID,
    CategoryName,
    ROUND(AVG(TotalQuantity), 2) AS AvgOrderQuantity
FROM CategoryOrderQty
GROUP BY CategoryID, CategoryName
ORDER BY AvgOrderQuantity DESC;
"""

In [45]:
# Read the results into a pandas DataFrame
df4 = pd.read_sql_query(query4, conn)
df4

   CategoryID    CategoryName  AvgOrderQuantity
0           4  Dairy Products            260.10
1           6    Meat/Poultry            214.67
2           1       Beverages            190.75
3           3     Confections            162.31
4           7         Produce            143.00
5           5  Grains/Cereals            130.29
6           8         Seafood            120.42
7           2      Condiments            115.25

```sql
-- Your code down below

```

|CategoryName                    |AvgOrderQuantity|
|--------------------------------|----------------|
|Beverages                       |24.6129         |
|Condiments                      |28.2245         |
|Confections                     |25.1190         |
|Dairy Products                  |26.0100         |
|Grains/Cereals                  |21.7143         |
|Meat/Poultry                    |25.7600         |
|Produce                         |21.6667         |
|Seafood                         |21.5672         |

# 5. Create a CTE to calculate the average order amount for each customer.

In [50]:

# Run your SQL query_5
query_5 = """
    SELECT o.CustomerID, c.CustomerName, AVG(od.Quantity * p.price) AS AvgOrderAmount
    FROM OrderDetails od
    JOIN Orders o ON od.OrderID = o.OrderID
    JOIN Customers c ON o.CustomerID = c.CustomerID
    JOIN Products p ON od.ProductID = p.ProductID
    GROUP BY o.CustomerID, c.CustomerName
    ORDER BY AvgOrderAmount DESC;
"""

In [51]:
# Read the results into a pandas DataFrame
df5 = pd.read_sql_query(query_5, conn)
df5

    CustomerID                        CustomerName  AvgOrderAmount
0           59                    Piccolo und mehr     4010.187500
1           73                       Simons bistro     2436.500000
2           62                       Queen Cozinha     1986.733333
3           51                      Mère Paillarde     1668.757143
4           71                  Save-a-lot Markets     1406.253750
..         ...                                 ...             ...
69          29              Galería del gastrónomo      148.250000
70          69                    Romero y tomillo      115.836250
71          13          Centro comercial Moctezuma       63.000000
72          27                      Franchi S.p.A.       62.460000
73           2  Ana Trujillo Emparedados y helados       55.500000

[74 rows x 3 columns]

```sql
-- Your code down below


```

|CustomerID                      |CustomerName|AvgOrderAmount|
|--------------------------------|------------|--------------|
|59                              |Piccolo und mehr|4014.2500     |
|73                              |Simons bistro|2444.3333     |
|62                              |Queen Cozinha|1991.6667     |
|51                              |Mère Paillarde|1673.8571     |
|71                              |Save-a-lot Markets|1407.2500     |
|76                              |Suprêmes délices|1345.8333     |
|81                              |Tradição Hipermercados|1315.6667     |
|7                               |Blondel père et fils|1174.4615     |
|89                              |White Clover Markets|1112.5000     |
|55                              |Old World Delicatessen|1079.5000     |
|20                              |Ernst Handel|1018.0000     |
|19                              |Eastern Connection|1004.8000     |
|68                              |Richter Supermarkt|976.6667      |
|72                              |Seven Seas Imports|934.0000      |
|63                              |QUICK-Stop  |908.5500      |
|25                              |Frankenversand|895.0667      |
|75                              |Split Rail Beer & Ale|854.7692      |
|65                              |Rattlesnake Canyon Grocery|838.2727      |
|52                              |Morgenstern Gesundkost|754.0000      |
|9                               |Bon app''   |750.4286      |
|37                              |Hungry Owl All-Night Grocers|733.5714      |
|35                              |HILARIÓN-Abastos|722.8333      |
|33                              |GROSELLA-Restaurante|690.0000      |
|34                              |Hanari Carnes|681.0000      |
|15                              |Comércio Mineiro|677.5000      |
|23                              |Folies gourmandes|672.3333      |
|10                              |Bottom-Dollar Marketse|664.0000      |
|31                              |Gourmet Lanchonetes|641.0000      |
|60                              |Princesa Isabel Vinhoss|628.5000      |
|5                               |Berglunds snabbköp|601.5556      |
|46                              |LILA-Supermercado|564.7692      |
|44                              |Lehmanns Marktstand|545.7500      |
|30                              |Godos Cocina Típica|515.0000      |
|3                               |Antonio Moreno Taquería|504.0000      |
|88                              |Wellington Importadora|503.8333      |
|47                              |LINO-Delicateses|500.0000      |
|56                              |Ottilies Käseladen|500.0000      |
|87                              |Wartian Herkku|492.5833      |
|24                              |Folk och fä HB|480.2222      |
|49                              |Magazzini Alimentari Riuniti|464.2857      |
|86                              |Die Wandernde Kuh|441.9091      |
|41                              |La maison d''Asie|437.8182      |
|8                               |Bólido Comidas preparadas|416.0000      |
|83                              |Vaffeljernet|411.0000      |
|14                              |Chop-suey Chinese|374.8333      |
|80                              |Tortuga Restaurante|357.4167      |

## 6. Sales Analysis with CTEs

Assume we have the Northwind database which contains tables like Orders, OrderDetails, and Products. Create a CTE that calculates the total sales for each product in the year 1997.

```sql
-- Your code down below

 ```

In [60]:
query_6 = """
SELECT p.ProductName, SUM(od.Quantity) AS TotalSales
FROM products p
JOIN OrderDetails od ON p.ProductID = od.ProductID
JOIN orders o ON od.OrderID = o.OrderID
WHERE strftime ("%Y", o.OrderDate) = "1997"
GROUP BY p.ProductName
ORDER BY TotalSales DESC;
"""

In [61]:
# Read the results into a pandas DataFrame
df6 = pd.read_sql_query(query_6, conn)
df6

                         ProductName  TotalSales
0             Gnocchi di nonna Alice         173
1                          Tourtière         126
2                            Geitost         119
3               Raclette Courdavault         115
4                              Chang         115
5                     Sirop d'érable         106
6                       Vegie-spread         100
7                      Côte de Blaye          99
8                       Alice Mutton          97
9                     Steeleye Stout          95
10               Sir Rodney's Scones          92
11                           Pavlova          86
12                     Zaanse koeken          85
13                    Tarte au sucre          75
14                       Fløtemysost          75
15                    Queso Cabrales          72
16               Gumbär Gummibärchen          72
17                         Chocolade          70
18                              Tofu          67
19               Scottish Longbreads          66
20                          Tunnbröd          60
21                          Maxilaku          60
22         Louisiana Hot Spiced Okra          60
23                 Camembert Pierrot          60
24        Teatime Chocolate Biscuits          57
25                 Rössle Sauerkraut          54
26                      Lakkalikööri          52
27                  Boston Crab Meat          52
28                Schoggi Schokolade          50
29                     Aniseed Syrup          50
30           Thüringer Rostbratwurst          45
31   Original Frankfurter grüne Soße          45
32                     Longlife Tofu          45
33         Wimmers gute Semmelknödel          43
34                  Valkoinen suklaa          40
35     Singaporean Hokkien Fried Mee          40
36                     Perth Pasties          40
37                      Gula Malacca          40
38                    Ravioli Angelo          35
39                  Gudbrandsdalsost          35
40                             Chais          34
41                         Spegesild          27
42   Jack's New England Clam Chowder          25
43              Rhönbräu Klosterbier          24
44                     Sasquatch Ale          20
45                        Röd Kaviar          20
46                   Mishi Kobe Niku          20
47  Louisiana Fiery Hot Pepper Sauce          20
48             Nord-Ost Matjeshering          18
49         Queso Manchego La Pastora          15
50                 Gorgonzola Telino          14
51               Gustaf's Knäckebröd          12
52                      Pâté chinois          10
53            Mozzarella di Giovanni          10
54                        Gravad lax          10
55                     Outback Lager           8
56                       Inlagd Sill           5
57                             Konbu           2

#### Expected result

|ProductName                     |TotalSales|
|--------------------------------|----------|
|Gnocchi di nonna Alice          |173       |
|Tourtière                       |126       |
|Geitost                         |119       |
|Chang                           |115       |
|Raclette Courdavault            |115       |
|Sirop d'érable                  |106       |
|Vegie-spread                    |100       |
|Côte de Blaye                   |99        |
|Alice Mutton                    |97        |
|Steeleye Stout                  |95        |
|Sir Rodney's Scones             |92        |
|Pavlova                         |86        |
|Zaanse koeken                   |85        |
|Fløtemysost                     |75        |
|Tarte au sucre                  |75        |